version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/" # Location of go.mod
    schedule:
      interval: "weekly"
      day: "sunday"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "deps"
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "weekly"
      day: "sunday"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "ci"
